export enum CUSTOM_ERRORS {
  USER_INPUT_ERROR = 'USER_INPUT_ERROR',
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
